language: ruby
script: rspec spec -f d

install:
  - gem update bundler
  - bundle install

rvm:
  - 1.9
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - 2.2.2
  - 2.3.1
  - jruby-19mode

  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

env:
  global:
    - VERBOSE=true
    - TIMEOUT=1
    - BENCHMARK_QUANTITY=100000
    - STREAM_FILE_SIZE=68

branches:
  only:
    - master

notifications:
  email:
    - adamluzsi@gmail.com
